Create TABLE PAISES(
    paises  NUMERIC(3) PRIMARY KEY,
    pais    VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE SEXOS(
    id_sexo NUMERIC(1) PRIMARY KEY,
    sexo VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE PUESTOS(
    puesto NUMERIC(3) PRIMARY KEY,
    puntos VARCHAR(25) NOT NULL
                       UNIQUE
);

CREATE TABLE COMPETICIONES(
    id_comp NUMERIC(3) PRIMARY KEY,
    competicion VARCHAR(25) NOT NULL UNIQUE,
    id_pais NUMERIC(3) REFERENCES PAISES
);

CREATE TABLE CORREDORES(
    id_corredor NUMERIC(3) PRIMARY KEY,
    nombre VARCHAR(25) NOT NULL,
    apellido1 VARCHAR(25),
    apellido2 VARCHAR(25),
    id_pais NUMERIC(3) REFERENCES PAISES,
    id_sexo NUMERIC(3) REFERENCES SEXOS
);

CREATE TABLE RANKING_HOMBRE(
    id_comp NUMERIC(3) REFERENCES COMPETICIONES,
    id_corredor NUMERIC(3) REFERENCES CORREDORES,
    puestos VARCHAR(25) REFERENCES PUESTOS,
    PRIMARY KEY (id_comp,id_corredor,puestos)
);

CREATE TABLE RANKING_MUJER(
     id_comp NUMERIC(3) REFERENCES COMPETICIONES,
    id_corredor NUMERIC(3) REFERENCES CORREDORES,
    puestos VARCHAR(25) REFERENCES PUESTOS,
    PRIMARY KEY (id_comp,id_corredor,puestos)
);